swagger: "2.0"
info:
  title: Azavea Climate Data API
  version: "0.1.0"
host: api.futurefeelslike.com
paths:
  /city:
    get:
      summary: List Cities
      description: |
        Retrieves a paginated GeoJson Feature Collection of available cities.
      parameters:
        - name: page
          in: query
          type: integer
          minimum: 1
          default: 1
          format: int64
          required: false
          description: |
            Page of paginated results to return
        - name: page_size
          in: query
          type: integer
          format: int32
          minimum: 1
          maximum: 100
          default: 20
          required: false
          description: |
            The maximum number of cities to be returned by the query.
      responses:
        200:
          description: A paginated GeoJson Feature Collection of City objects
          schema:
            type: object
