version: '2.1'
services:
  django:
    image: "cc-api:${GIT_COMMIT:-latest}"
    environment:
      - COMMIT=${GIT_COMMIT}
      - CC_S3STORAGE_BUCKET=${CC_S3STORAGE_BUCKET:-climate-change-api-staging}

  nginx:
    image: "cc-nginx:${GIT_COMMIT:-latest}"

  dredd:
    build:
      context: ./dredd
      dockerfile: Dockerfile
    links:
      - django
    volumes:
      - ./dredd.yml:/dredd.yml
      - ./hooks.py:/hooks.py
      - ./doc/source/openapi/climate_api.yml:/doc/source/openapi/climate_api.yml
