version: '2'
services:
  django:
    image: cc-api:${GIT_COMMIT}
    environment:
      COMMIT: ${GIT_COMMIT}
      CC_S3STORAGE_BUCKET: ${CC_S3STORAGE_BUCKET}
  nginx:
    image: cc-nginx:${GIT_COMMIT}
