version: '2'
services:
  django:
    build:
      context: ./django
      dockerfile: Dockerfile
    environment:
      CC_DEBUG: 'true'
      DJANGO_LOG_LEVEL: 'INFO'
      AWS_PROFILE: 'climate'
      CC_S3STORAGE_BUCKET: 'climate-change-api'
      AWS_CACHE_DURATION: 31536000
      COMMIT:
    ports:
      - "8080:8080"
      - "8082:8082"
    links:
      - postgres
    depends_on:
      - postgres
    volumes:
      - .:/opt
      - $HOME/.aws:/root/.aws:ro
  postgres:
    image: quay.io/azavea/postgis:9.5.3
    environment:
      POSTGRES_USER: climate
      POSTGRES_PASSWORD: climate
      POSTGRES_DB: climate
    ports:
      - "5432:5432"
