version: '2'
services:
  django:
    build:
      context: ./django
      dockerfile: Dockerfile
    environment:
      CC_DEBUG: 'true'
      DEV_USER: '${DEV_USER}'
      DJANGO_LOG_LEVEL: 'INFO'
      AWS_PROFILE: '${AWS_PROFILE}'
      AWS_CACHE_DURATION: 31536000
      CC_REGISTRATION_OPEN:
      COMMIT:
    ports:
      - "8080:8080"
      - "8082:8082"
    links:
      - memcached
      - postgres
    depends_on:
      - memcached
      - postgres
    volumes:
      - .:/opt
      - ./nginx/srv/dist:/opt/doc/build
      - $HOME/.aws:/root/.aws:ro

  memcached:
    image: memcached:1.4-alpine
    command: [memcached, -I, 8M, -m, '256']

  postgres:
    image: quay.io/azavea/postgis:9.5.3
    environment:
      POSTGRES_USER: climate
      POSTGRES_PASSWORD: climate
      POSTGRES_DB: climate
    ports:
      - "5432:5432"
  
  docs:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8088:443"
    volumes:
     - ./nginx/srv/dist/:/srv/dist/
     - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./nginx/etc/nginx/includes/:/etc/nginx/includes/
     - ./nginx/etc/nginx/conf.d/docs/:/etc/nginx/conf.d/

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    links:
      - django
    ports:
      - "8088:443"
    depends_on:
      - django
    volumes:
      - ./nginx/srv/dist/:/srv/dist/
      - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/nginx/includes/:/etc/nginx/includes/
      - ./nginx/etc/nginx/conf.d/app/:/etc/nginx/conf.d/