version: '2'
services:
  django:
    build:
      context: ./django
      dockerfile: Dockerfile
    environment:
      CC_DEBUG: 'true'
      DEV_USER: '${DEV_USER}'
      DJANGO_LOG_LEVEL: 'INFO'
      AWS_PROFILE: '${AWS_PROFILE}'
      AWS_CACHE_DURATION: 31536000
      CC_REGISTRATION_OPEN:
      COMMIT:
    ports:
      - "8080:8080"
      - "8082:8082"
    links:
      - memcached
      - postgres
    depends_on:
      - memcached
      - postgres
    volumes:
      - .:/opt
      - $HOME/.aws:/root/.aws:ro
  memcached:
    image: memcached:1.4-alpine
  postgres:
    image: quay.io/azavea/postgis:9.5.3
    environment:
      POSTGRES_USER: climate
      POSTGRES_PASSWORD: climate
      POSTGRES_DB: climate
    ports:
      - "5432:5432"
