dry-run: null
hookfiles: ./django/climate_change_api/hooks.py
language: python
sandbox: false
server: ./scripts/server
server-wait: 3
init: false
names: false
only: []
reporter: apiary
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
hooks-worker-timeout: 500
hooks-worker-connect-timeout: 1000
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 500
hooks-worker-term-retry: 500
hooks-worker-handler-host: localhost
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: doc/source/openapi/climate_api.yml
endpoint: 'http://localhost:8083'
