#cloud-config

package_upgrade: true

packages:
 - aws-cli
 - unzip

write_files:
  - path: /etc/sysconfig/docker
    permissions: 0644
    owner: root:root
    content: |
      # The max number of open files for the daemon itself, and all
      # running containers.  The default value of 1048576 mirrors the value
      # used by the systemd service unit.
      DAEMON_MAXFILES=1048576

      # Additional startup options for the Docker daemon, for example:
      # OPTIONS="--ip-forward=true --iptables=true"
      # By default we limit the number of open files per container
      #OPTIONS="--default-ulimit nofile=1024:4096 --log-driver=awslogs --log-opt awslogs-region=us-east-1 --log-opt awslogs-group=${stack_type}"
  - path: /etc/ecs/ecs.config
    permissions: 0644
    owner: root:root
    content: |
      ECS_CLUSTER=cc-api-${stack_type}
