# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 19:31
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=40)),
                ('admin_name', models.CharField(max_length=40)),
                ('population', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClimateData',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField()),
                ('day_of_year', models.PositiveSmallIntegerField()),
                ('tasmin', models.FloatField(null=True)),
                ('tasmax', models.FloatField(null=True)),
                ('pr', models.FloatField(null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate_data.City')),
            ],
        ),
        migrations.CreateModel(
            name='ClimateModel',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='climatedata',
            name='climate_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate_data.ClimateModel'),
        ),
    ]
