# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 13:55


import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=40)),
                ('admin_name', models.CharField(max_length=40)),
                ('climate', models.CharField(max_length=40, null=True)),
                ('precip', models.CharField(max_length=40, null=True)),
                ('temp', models.CharField(max_length=40, null=True)),
                ('continent', models.CharField(max_length=20, null=True)),
                ('gdp_md_est', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClimateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('day_of_year', models.PositiveSmallIntegerField()),
                ('tasmin', models.FloatField(null=True)),
                ('tasmax', models.FloatField(null=True)),
                ('pr', models.FloatField(null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate_data.City')),
            ],
        ),
        migrations.CreateModel(
            name='ClimateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PopulationCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('pop', models.PositiveIntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate_data.City')),
            ],
        ),
        migrations.AddField(
            model_name='climatedata',
            name='climate_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate_data.ClimateModel'),
        ),
        migrations.AlterUniqueTogether(
            name='populationcount',
            unique_together=set([('city', 'year')]),
        ),
        migrations.AlterUniqueTogether(
            name='climatedata',
            unique_together=set([('city', 'climate_model', 'year', 'day_of_year')]),
        ),
    ]
