# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='populationcount',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='populationcount',
            name='city',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='admin_name',
            new_name='admin',
        ),
        migrations.RemoveField(
            model_name='city',
            name='climate',
        ),
        migrations.RemoveField(
            model_name='city',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='city',
            name='gdp_md_est',
        ),
        migrations.RemoveField(
            model_name='city',
            name='precip',
        ),
        migrations.RemoveField(
            model_name='city',
            name='temp',
        ),
        migrations.AddField(
            model_name='city',
            name='population',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PopulationCount',
        ),
    ]
