# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-12 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationCount',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField()),
                ('pop', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='city',
            name='population',
        ),
        migrations.AddField(
            model_name='city',
            name='climate',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='continent',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='gdp_md_est',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='precip',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='temp',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='climatedata',
            unique_together=set([('city', 'climate_model', 'year', 'day_of_year')]),
        ),
        migrations.AddField(
            model_name='populationcount',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate_data.City'),
        ),
        migrations.AlterUniqueTogether(
            name='populationcount',
            unique_together=set([('city', 'year')]),
        ),
    ]
