# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0002_auto_20160513_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatedata',
            name='pr',
            field=models.FloatField(help_text='Precipitation (mean of the daily precipitation rate), kg m-2 s-1', null=True),
        ),
        migrations.AlterField(
            model_name='climatedata',
            name='tasmax',
            field=models.FloatField(help_text='Daily Maximum Near-Surface Air Temperature, Degrees Kelvin', null=True),
        ),
        migrations.AlterField(
            model_name='climatedata',
            name='tasmin',
            field=models.FloatField(help_text='Daily Minimum Near-Surface Air Temperature, Degrees Kelvin', null=True),
        ),
    ]
