# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 16:36


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0003_auto_20160516_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='population',
        ),
    ]
