# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0004_remove_city_population'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set([('name', 'admin')]),
        ),
    ]
