# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-17 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0005_auto_20160516_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatedata',
            name='tasmax',
            field=models.FloatField(help_text='Daily Maximum Near-Surface Air Temperature, Kelvin', null=True),
        ),
        migrations.AlterField(
            model_name='climatedata',
            name='tasmin',
            field=models.FloatField(help_text='Daily Minimum Near-Surface Air Temperature, Kelvin', null=True),
        ),
    ]
