# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 12:26


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0007_auto_20160520_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, unique=True)),
                ('description', models.CharField(blank=True, max_length=4096, null=True)),
            ],
        ),
    ]
