# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 14:58


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0012_auto_20160608_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='climatemodel',
            name='base_time',
            field=models.DateField(null=True),
        ),
    ]
