# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 19:42


import climate_data.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0014_auto_20160715_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateDataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('climate_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate_data.ClimateModel')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate_data.Scenario')),
            ],
        ),
        migrations.AddField(
            model_name='climatedata',
            name='data_source',
            field=climate_data.models.TinyForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='climate_data.ClimateDataSource'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='climatedata',
            unique_together=set([('city', 'data_source', 'day_of_year')]),
        ),
        migrations.RemoveField(
            model_name='climatedata',
            name='climate_model',
        ),
        migrations.RemoveField(
            model_name='climatedata',
            name='scenario',
        ),
        migrations.RemoveField(
            model_name='climatedata',
            name='year',
        ),
    ]
