# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 19:54


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0015_auto_20160719_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='climatedatasource',
            old_name='climate_model',
            new_name='model',
        ),
        migrations.AlterUniqueTogether(
            name='climatedatasource',
            unique_together=set([('model', 'scenario', 'year')]),
        ),
    ]
