# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 16:28
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    """
    Adds a _geog field to enable accurate indexed distance searching and fills it with
    the existing geometry field values.
    """

    dependencies = [
        ('climate_data', '0016_auto_20160719_1954'),
    ]

    add_geography = "UPDATE climate_data_city SET _geog=geom;"

    operations = [
        migrations.AddField(
            model_name='city',
            name='_geog',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
        migrations.RunSQL(add_geography, migrations.RunSQL.noop),
        migrations.AlterField(
            model_name='city',
            name='_geog',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
