# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-18 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0018_auto_20160803_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatemodel',
            name='name',
            field=models.CharField(choices=[('ACCESS1-0', 'ACCESS1-0'), ('BNU-ESM', 'BNU-ESM'), ('CCSM4', 'CCSM4'), ('CESM1-BGC', 'CESM1-BGC'), ('CNRM-CM5', 'CNRM-CM5'), ('CSIRO-Mk3-6-0', 'CSIRO-Mk3-6-0'), ('CanESM2', 'CanESM2'), ('GFDL-CM3', 'GFDL-CM3'), ('GFDL-ESM2G', 'GFDL-ESM2G'), ('GFDL-ESM2M', 'GFDL-ESM2M'), ('IPSL-CM5A-LR', 'IPSL-CM5A-LR'), ('IPSL-CM5A-MR', 'IPSL-CM5A-MR'), ('MIROC-ESM-CHEM', 'MIROC-ESM-CHEM'), ('MIROC-ESM', 'MIROC-ESM'), ('MIROC5', 'MIROC5'), ('MPI-ESM-LR', 'MPI-ESM-LR'), ('MPI-ESM-MR', 'MPI-ESM-MR'), ('MRI-CGCM3', 'MRI-CGCM3'), ('NorESM1-M', 'NorESM1-M'), ('bcc-csm1-1', 'bcc-csm1-1'), ('inmcm4', 'inmcm4')], max_length=40, unique=True),
        ),
    ]
