# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 13:45
from __future__ import unicode_literals

import climate_data.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0019_auto_20160818_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='map_cell',
            field=climate_data.models.TinyForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='climate_data.ClimateDataCell'),
        ),
    ]
