# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0019_auto_20160818_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='climatemodel',
            name='label',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='label',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
