# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0020_auto_20160901_1345'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='climatedata',
            index_together=set([('map_cell', 'data_source')]),
        ),
    ]
