# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0021_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatemodel',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
