# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-02 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0022_auto_20160901_1919'),
        ('climate_data', '0021_auto_20160901_2037'),
    ]

    operations = [
    ]
