# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-22 15:26


import climate_data.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0023_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricAverageClimateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_day', models.CharField(max_length=5)),
                ('tasmin', models.FloatField(help_text='Historic Average Daily Minimum Near-Surface Air Temperature 1961-1990, Kelvin', null=True)),
                ('tasmax', models.FloatField(help_text='Historic Average Daily Maximum Near-Surface Air Temperature 1961-1990, Kelvin', null=True)),
                ('pr', models.FloatField(help_text='Historic Average Precipitation (mean of the daily precipitation rate) 1961-1990, kg m-2 s-1', null=True)),
                ('city', climate_data.models.TinyForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate_data.City')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='historicaverageclimatedata',
            unique_together=set([('city', 'month_day')]),
        ),
        migrations.AlterIndexTogether(
            name='historicaverageclimatedata',
            index_together=set([('city', 'month_day')]),
        ),
    ]
