# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-29 20:14
from __future__ import unicode_literals

import climate_data.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0024_auto_20160922_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateDataBaseline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precip_99p', models.FloatField(help_text='99th percentile historic precipitation by day', null=True)),
                ('map_cell', climate_data.models.TinyForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseline', to='climate_data.ClimateDataCell')),
                ('model', climate_data.models.TinyForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate_data.ClimateModel')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='climatedatabaseline',
            unique_together=set([('map_cell', 'model')]),
        ),
    ]
