# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-10 20:55
from __future__ import unicode_literals

import climate_data.models
from django.db import migrations, models
import django.db.models.deletion


def clear_climate_data(apps, schema_editor):
    climate_data.models.HistoricAverageClimateData.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0025_climatedatabaseline'),
    ]

    operations = [
        migrations.RunPython(clear_climate_data, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name='historicaverageclimatedata',
            name='day_of_year',
            field=models.PositiveSmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaverageclimatedata',
            name='map_cell',
            field=climate_data.models.TinyForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='climate_data.ClimateDataCell'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='historicaverageclimatedata',
            unique_together=set([('map_cell', 'day_of_year')]),
        ),
        migrations.AlterIndexTogether(
            name='historicaverageclimatedata',
            index_together=set([('map_cell', 'day_of_year')]),
        ),
        migrations.RemoveField(
            model_name='historicaverageclimatedata',
            name='city',
        ),
        migrations.RemoveField(
            model_name='historicaverageclimatedata',
            name='month_day',
        ),
        migrations.RunPython(migrations.RunPython.noop, reverse_code=clear_climate_data),
    ]
