# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-20 17:57
from __future__ import unicode_literals

import climate_data.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0026_auto_20161010_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaverageclimatedata',
            name='map_cell',
            field=climate_data.models.TinyForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historic_average', to='climate_data.ClimateDataCell'),
        ),
    ]
