# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-29 14:03
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0028_city_population'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityBoundary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('source', models.CharField(max_length=64)),
                ('boundary_type', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='boundary',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='climate_data.CityBoundary'),
        ),
    ]
