# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-02 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0029_auto_20161129_1403'),
        ('climate_data', '0029_auto_20161122_2151'),
    ]

    operations = [
    ]
