# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-08 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0030_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatedatabaseline',
            name='tasmin',
            field=models.FloatField(help_text='Historic greatest daily minimum temperature for this percentile from 1961-1990', null=True),
        ),
    ]
