# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-16 13:52


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0033_swap_city_cityboundary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='boundary_temp',
        ),
        migrations.RenameField(
            model_name='cityboundary',
            old_name='city_temp',
            new_name='city',
        ),
    ]
