# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-20 00:52


from django.db import migrations

def delete_city_boundaries_with_null_city(apps, schema_editor):
    """ Before making city ref required, remove any boundaries with null refs

    These boundaries don't make sense anyways

    """
    CityBoundary = apps.get_model('climate_data', 'CityBoundary')
    CityBoundary.objects.filter(city__isnull=True).delete()


def reverse_delete_city_boundaries(apps, schema_editor):
    """ Reverse is a no-op going backwards """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0034_auto_20161216_1352'),
    ]

    operations = [
        migrations.RunPython(delete_city_boundaries_with_null_city, reverse_delete_city_boundaries)
    ]
