# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-25 20:36


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0029_auto_20161121_1753'),
        ('climate_data', '0036_auto_20161220_0056'),
    ]

    operations = [
    ]
