# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-25 20:59


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0037_merge'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='region',
            unique_together=set([('level1', 'level2')]),
        ),
    ]
