# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-26 13:17


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0038_auto_20170125_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='climate_data.Region'),
        ),
    ]
