# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-01 21:25


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0039_auto_20170126_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='climatedatasource',
            name='import_completed',
            field=models.BooleanField(default=False),
        ),
    ]
