# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-05 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0041_auto_20170414_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricDateRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveSmallIntegerField(help_text='Inclusive starting year of the period')),
                ('end_year', models.PositiveSmallIntegerField(help_text='Exclusive ending year of the period')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='historicdaterange',
            unique_together=set([('start_year', 'end_year')]),
        ),
    ]
