# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-05 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0041_auto_20170414_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricDateRange',
            fields=[
                ('start_year', models.PositiveSmallIntegerField(help_text='Inclusive start year of the period', unique=True, primary_key=True, serialize=False)),
                ('end_year', models.PositiveSmallIntegerField(help_text='Inclusive ending year of the period')),
            ],
        )
    ]
