# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-05 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0041_auto_20170414_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricDateRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(max_length=20, help_text='30 year historic period, e.g. 1961-1990')),
            ],
        ),
    ]
