# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-05 20:58
from __future__ import unicode_literals

import climate_data.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0042_historicdaterange'),
    ]

    operations = [
        migrations.AddField(
            model_name='climatedatabaseline',
            name='historical_range',
            field=climate_data.models.TinyForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='climate_data.HistoricDateRange'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='climatedatabaseline',
            name='pr',
            field=models.FloatField(help_text='Historic greatest daily precipitation for this percentile for a 30 yr period', null=True),
        ),
        migrations.AlterField(
            model_name='climatedatabaseline',
            name='tasmax',
            field=models.FloatField(help_text='Historic greatest daily maximum temperature for this percentile for a 30 yr period', null=True),
        ),
        migrations.AlterField(
            model_name='climatedatabaseline',
            name='tasmin',
            field=models.FloatField(help_text='Historic greatest daily minimum temperature for this percentile for a 30 yr period', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='climatedatabaseline',
            unique_together=set([('map_cell', 'percentile', 'historical_range')]),
        ),
    ]
