# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-05 20:58
from __future__ import unicode_literals

import climate_data.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0042_historicdaterange'),
    ]

    operations = [
        migrations.AddField(
            model_name='climatedatabaseline',
            name='date_range',
            field=climate_data.models.TinyForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='climate_data.HistoricDateRange'),
            preserve_default=False,
        ),
    ]
