# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-06 19:47
from __future__ import unicode_literals

import climate_data.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0043_climatedatabaseline_historic_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaverageclimatedata',
            name='historic_range',
            field=climate_data.models.TinyForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate_data.HistoricDateRange', null=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='historicaverageclimatedata',
            unique_together=set([('map_cell', 'day_of_year', 'historic_range')]),
        ),
        migrations.AlterIndexTogether(
            name='historicaverageclimatedata',
            index_together=set([('map_cell', 'day_of_year', 'historic_range')]),
        ),
    ]
