# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-27 16:58
from __future__ import unicode_literals

import climate_data.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0045_auto_20170607_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricAverageClimateDataYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasmin', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), help_text='Historic Average Daily Minimum Near-Surface Air Temperature in Kelvin', size=None)),
                ('tasmax', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), help_text='Historic Average Daily Maximum Near-Surface Air Temperature in Kelvin', size=None)),
                ('pr', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), help_text='Historic Average Precipitation (mean of the daily precipitation rate) in kg/s/m^2', size=None)),
                ('historic_range', climate_data.models.TinyForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='climate_data.HistoricDateRange')),
                ('map_cell', climate_data.models.TinyForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historic_average_array', to='climate_data.ClimateDataCell')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='historicaverageclimatedatayear',
            unique_together=set([('map_cell', 'historic_range')]),
        ),
        migrations.AlterIndexTogether(
            name='historicaverageclimatedatayear',
            index_together=set([('map_cell', 'historic_range')]),
        ),
    ]
