# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-18 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0046_auto_20170727_1658'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='climatedata',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='climatedata',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='climatedata',
            name='data_source',
        ),
        migrations.RemoveField(
            model_name='climatedata',
            name='map_cell',
        ),
        migrations.DeleteModel(
            name='ClimateData',
        ),
    ]
