# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-18 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0047_auto_20170818_2005'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historicaverageclimatedata',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='historicaverageclimatedata',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='historicaverageclimatedata',
            name='historic_range',
        ),
        migrations.RemoveField(
            model_name='historicaverageclimatedata',
            name='map_cell',
        ),
        migrations.DeleteModel(
            name='HistoricAverageClimateData',
        ),
    ]
