# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0048_auto_20170818_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, unique=True)),
                ('label', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=4096, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
