# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 19:48
from __future__ import unicode_literals

from django.db import migrations

def populate_climatedatacell_dataset(apps, schema_editor):
    ClimateDataCell = apps.get_model('climate_data', 'ClimateDataCell')
    ClimateDataset = apps.get_model('climate_data', 'ClimateDataset')

    gddp = ClimateDataset.objects.get(name='NEX-GDDP')

    ClimateDataCell.objects.filter(dataset__isnull=True).update(dataset=gddp)


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0049_auto_20170816_1947'),
    ]

    operations = [
        migrations.RunPython(populate_climatedatacell_dataset, migrations.RunPython.noop)
    ]
