# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 19:48
from __future__ import unicode_literals

from django.db import connection, migrations

def populate_climatedatacell_dataset(apps, schema_editor):
    ClimateDataCell = apps.get_model('climate_data', 'ClimateDataCell')
    ClimateDataset = apps.get_model('climate_data', 'ClimateDataset')

    gddp = ClimateDataset.objects.get(name='NEX-GDDP')
    with connection.cursor() as cursor:
        sql = ("UPDATE {table} SET dataset_id = %s WHERE dataset_id is null"
               .format(table=ClimateDataCell._meta.db_table))
        cursor.execute(sql, [gddp.id])


def reverse(apps, schema_editor):
    """Reverse operation allowed, and is a no-op."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0049_auto_20170816_1947'),
    ]

    operations = [
        migrations.RunPython(populate_climatedatacell_dataset, reverse)
    ]
