# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 20:01
from __future__ import unicode_literals

import climate_data.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0050_auto_20170816_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatedatacell',
            name='dataset',
            field=climate_data.models.TinyForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_cells', to='climate_data.ClimateDataset'),
        ),
        migrations.AlterUniqueTogether(
            name='climatedatacell',
            unique_together=set([('lat', 'lon', 'dataset')]),
        ),
    ]
