# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-22 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    def migrate_city_cells_many_to_many(apps, schema_editor):
        City = apps.get_model('climate_data', 'City')
        ClimateDataCityCell = apps.get_model('climate_data', 'ClimateDataCityCell')
        ClimateDataset = apps.get_model('climate_data', 'ClimateDataset')

        gddp = ClimateDataset.objects.get(name='NEX-GDDP')

        city_data = City.objects.all().values('id', 'map_cell_id')

        # Create a default many-to-many relationship for GDDP for all Cities and their current
        # one-to-many map cell foreign key
        city_cell_objects = (ClimateDataCityCell(
            city_id=row['id'],
            map_cell_id=row['map_cell_id'],
            datasource=gddp
        ) for row in city_data)

        ClimateDataCityCell.objects.bulk_create(city_cell_objects)

    dependencies = [
        ('climate_data', '0052_auto_20170822_2036'),
    ]

    operations = [
        migrations.RunPython(migrate_city_cells_many_to_many, migrations.RunPython.noop)
    ]
