# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-22 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    def migrate_restore_city_cell_foreign_key(apps, schema_editor):
        """If we reverse this migration, set City.map_cell to the city's NEX-GDDP cell."""
        City = apps.get_model('climate_data', 'City')
        city_data = (City.objects.all().values_list('id', 'map_cell_set__map_cell_id')
                     .filter(map_cell_set__dataset__name='NEX-GDDP'))

        for id, cell_id in city_data:
            City.objects.filter(id=id).update(map_cell=cell_id)

    dependencies = [
        ('climate_data', '0053_migrate_city_cells'),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, migrate_restore_city_cell_foreign_key),
        migrations.RemoveField(
            model_name='city',
            name='map_cell',
        ),
    ]
