# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-22 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0053_migrate_city_cells'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='map_cell',
        ),
    ]
