# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-22 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0054_auto_20170822_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climatedatacell',
            name='dataset',
        ),
        migrations.AlterUniqueTogether(
            name='climatedatacell',
            unique_together=set([('lat', 'lon')]),
        ),
    ]
