# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-01 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0056_remove_city_map_cell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatedatacell',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='climatedatacell',
            name='lon',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
