# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-08 13:16
from __future__ import unicode_literals

import logging

from django.db import migrations


logger = logging.getLogger(__name__)


NEX_GDDP_MODELS = [
    'ACCESS1-0',
    'BNU-ESM',
    'CCSM4',
    'CESM1-BGC',
    'CNRM-CM5',
    'CSIRO-Mk3-6-0',
    'CanESM2',
    'GFDL-CM3',
    'GFDL-ESM2G',
    'GFDL-ESM2M',
    'IPSL-CM5A-LR',
    'IPSL-CM5A-MR',
    'MIROC-ESM-CHEM',
    'MIROC-ESM',
    'MIROC5',
    'MPI-ESM-LR',
    'MPI-ESM-MR',
    'MRI-CGCM3',
    'NorESM1-M',
    'bcc-csm1-1',
    'inmcm4',
]

LOCA_MODELS = [
    'ACCESS1-0',
    'ACCESS1-3',
    'CCSM4',
    'CESM1-BGC',
    'CESM1-CAM5',
    'CMCC-CM',
    'CMCC-CMS',
    'CMCC-CM5',
    'CSIRO-Mk3-6-0',
    'CanESM2',
    'EC-EARTH',
    'FGOALS-g2',
    'GFDL-CM3',
    'GFDL-ESM2G',
    'GFDL-ESM2M',
    'GISS-E2-H',
    'GISS-E2-R',
    'HadGEM2-AO',
    'HadGEM2-CC',
    'HadGEM2-ES',
    'IPSL-CM5A-LR',
    'IPSL-CM5A-MR',
    'MIROC-ESM-CHEM',
    'MIROC-ESM',
    'MIROC5',
    'MPI-ESM-LR',
    'MPI-ESM-MR',
    'MRI-CGCM3',
    'NorESM1-M',
    'bcc-csm1-1-m',
    'bcc-csm1-1',
    'inmcm4',
]


def add_missing_climate_models(apps, schema_editor):
    """Add climate models to the db that are missing from the list.

    To properly associate models with datasets in the next two migrations, we
    need to ensure that all of the models we care about exist in the DB.

    We do not destroy data here, only create missing objects.

    """
    ClimateModel = apps.get_model('climate_data', 'ClimateModel')
    all_models = set(NEX_GDDP_MODELS + LOCA_MODELS)
    existing_models = set(ClimateModel.objects.all().values_list('name', flat=True))
    new_models = all_models - existing_models
    for model in new_models:
        ClimateModel.objects.create(name=model, label=model)


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0057_auto_20170901_1656'),
    ]

    operations = [
        migrations.RunPython(add_missing_climate_models, migrations.RunPython.noop)
    ]
