# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-14 13:18
from __future__ import unicode_literals

from django.db import migrations


def fix_loca_model_list(apps, schema_editor):
    ClimateModel = apps.get_model('climate_data', 'ClimateModel')
    ClimateDataset = apps.get_model('climate_data', 'ClimateDataset')

    # Remove CMCC-CM5, its not a real model for either dataset, was added via typo
    ClimateModel.objects.get(name='CMCC-CM5').delete()
    # Associate CNRM-CM5 with LOCA
    loca = ClimateDataset.objects.get(name='LOCA')
    loca.models.add(ClimateModel.objects.get(name='CNRM-CM5'))


def revert_loca_model_list(apps, schema_editor):
    # Revert on reverse so DB is consistent with original data migration
    ClimateModel = apps.get_model('climate_data', 'ClimateModel')
    ClimateDataset = apps.get_model('climate_data', 'ClimateDataset')

    loca = ClimateDataset.objects.get(name='LOCA')
    cmcc_cm5 = ClimateModel.objects.create(name='CMCC-CM5', label='CMCC-CM5')
    loca.models.add(cmcc_cm5)

    loca.models.remove(ClimateModel.objects.get(name='CNRM-CM5'))


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0060_associate_datasets_and_models'),
    ]

    operations = [
        migrations.RunPython(fix_loca_model_list, revert_loca_model_list)
    ]
