# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-14 01:38
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0062_city_is_coastal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coastline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField(unique=True)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='coastline',
            unique_together=set([('objectid',)]),
        ),
    ]
