# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-14 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0062_add_dataset_specificity_to_historic_calculations'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_coastal',
            field=models.BooleanField(default=False),
        ),
    ]
