# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-05 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0064_coastline'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='alias',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
