# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-08 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0066_auto_20180627_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='climatedataset',
            name='cell_size_x',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='climatedataset',
            name='cell_size_y',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
