# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-08 18:00
from __future__ import unicode_literals
from decimal import Decimal
import logging

from django.db import migrations


logger = logging.getLogger(__name__)


def set_climatedatacell_cell_sizes(apps, schema_editor):
    CELL_SIZES = {
        'LOCA': {
            'x': Decimal(0.0625),
            'y': Decimal(0.0625),
        },
        'NEX-GDDP': {
            'x': Decimal(0.25),
            'y': Decimal(0.25),
        }
    }

    ClimateDataset = apps.get_model('climate_data', 'ClimateDataset')
    for dataset in ClimateDataset.objects.all():
        try:
            cell_size = CELL_SIZES[dataset.name]
        except KeyError:
            logger.warning('No CELL_SIZE found for dataset: {}'.format(dataset.name))
            continue
        dataset.cell_size_x = cell_size['x']
        dataset.cell_size_y = cell_size['y']
        dataset.save()


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0067_add_climatedatacell_cell_sizes'),
    ]

    operations = [
        migrations.RunPython(set_climatedatacell_cell_sizes, migrations.RunPython.noop)
    ]
