# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-18 20:30
from __future__ import unicode_literals

from django.contrib.gis.geos import Point
from django.db import migrations


def set_climatedatacell_geom(apps, schema_editor):
    ClimateDataCell = apps.get_model('climate_data', 'ClimateDataCell')
    for cell in ClimateDataCell.objects.all():
        # Convert saved lon [0, 360) back to [-180, 180)
        lon = cell.lon if cell.lon < 180 else cell.lon - 360
        cell.geom = Point(float(lon), float(cell.lat), srid=4326)
        cell.save()


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0069_add_climatedatacell_geom'),
    ]

    operations = [
        migrations.RunPython(set_climatedatacell_geom, migrations.RunPython.noop)
    ]
