# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-05 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0070_set_climatedatacell_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='climatedatacell',
            name='is_coastal',
            field=models.BooleanField(default=False),
        ),
    ]
