# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-10 20:45
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0071_add_climatedatacell_iscoastal'),
    ]

    operations = [
        migrations.AddField(
            model_name='climatedatacell',
            name='geog',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
