# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0073_set_climatedatacell_geog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='climatemodel',
            options={'ordering': ['name']},
        ),
    ]
