#!/bin/bash
set -e

if [[ -n "${CC_DEBUG}" ]]; then
    set -x
fi

if [[ -n "${GIT_COMMIT}" ]]; then
    GIT_COMMIT="${GIT_COMMIT:0:7}"
else
    GIT_COMMIT="$(git rev-parse --short HEAD)"
fi

echo "GIT_COMMIT:${GIT_COMMIT}"
DIR="$(dirname "$0")"

function usage() {
    echo -n \
         "Usage: $(basename "$0")
Build application for staging or a release.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        ${DIR}/update

        echo "Building django and nginx"
        GIT_COMMIT="${GIT_COMMIT}" docker-compose \
                  -f "${DIR}/../docker-compose.yml" \
                  -f "${DIR}/../docker-compose.test.yml"\
                  build django nginx

        echo "Running tests"
        GIT_COMMIT="${GIT_COMMIT}" ${DIR}/test
        echo "All tests pass!"

        echo "Building docs"
        ${DIR}/docs
            
        echo "[DRY RUN] Uploading docs and static files to S3..."
        aws --profile "${AWS_PROFILE}" s3 sync --delete --dryrun \
          "${DIR}/../nginx/srv/dist/html" "s3://${CC_DOCS_FILES_BUCKET}"

        docker-compose -f docker-compose.yml \
                       -f docker-compose.test.yml \
                       run --rm --entrypoint "./manage.py" \
                       django "collectstatic" "--noinput"

        echo "[DRY RUN] Upload complete!"

    fi
fi
