#!/bin/bash
set -eu

function usage() {
    echo -n \
"Usage: $(basename "$0")
Builds documentation served in development
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        docker-compose build django
        docker-compose run --rm --entrypoint "/bin/bash -c" "django" \
                                             "cd ../../doc; sphinx-build -b html -d build/doctrees source build/html -a"
    fi
    exit
fi
