#!/bin/bash

set -eu

cd `dirname "$0"`

function usage() {
    echo -n \
"Usage: $(basename "$0") <component>
Serve application components in development.

<component> is one of:
  - app (default if not provided)
  - docs

"
}


if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    elif [ "${1:-}" = "docs" ]
    then
      cd ../doc/build/html && python -m SimpleHTTPServer 8088
    else
        pushd ..
            docker-compose up
        popd
    fi
    exit
fi
