#!/bin/bash

set -eu

function usage() {
    echo -n \
"Usage: $(basename "$0") <component>
Serve application components in development.

<component> is one of:
  - app (default if not provided)
  - docs

"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    elif [ "${1:-}" = "docs" ]
    then
        # Build the docs first if they don't yet exist
        if [ ! -d "./doc/build/html" ]
        then
            ./scripts/docs
        fi
        cd ./doc/build/html && python -m SimpleHTTPServer 8088
    else
        docker-compose up
    fi
    exit
fi
