#!/bin/bash

set -eu

function usage() {
    echo -n \
"Usage: $(basename "$0") <component>
Serve application components in development.

"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        # Build the docs first if they don't yet exist
        if [ ! -d "./doc/build/html" ]
        then
            ./scripts/docs
        fi
        docker-compose up
    fi
    exit
fi
