#!/bin/bash

set -eu

function usage() {
    echo -n \
"Usage: $(basename "$0")

Setup an initial development environment by setting up a VM and installing dependencies.

"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        vagrant up --provision
        vagrant ssh -c "cd climate-change-api && ./scripts/update"
    fi
    exit
fi
