#!/bin/bash

set -eu

function usage() {
    echo -n \
"Usage: $(basename "$0")

Run application tests.

"
}

function createTestUser() {
    echo "Creating test user"
    echo "ClimateUser.objects.create_superuser('testuser@testing.com','thisisatest')" | ./scripts/console django "./manage.py shell_plus"
}

function deleteTestUser() {
    echo "Deleting test user"
    echo "ClimateUser.objects.get(email='testuser@testing.com').delete()" | ./scripts/console django "./manage.py shell_plus"
}

function interceptError() {
    #Catch and clean upon bash error to ensure testing idempotence
    exitcode=$?
    deleteTestUser
    exit $exitcode
}


if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        docker-compose \
            run --rm --entrypoint "./manage.py" \
            django migrate --noinput

        docker-compose \
            run --rm --entrypoint "./manage.py" \
            django loaddata scenarios

        docker-compose \
            run --rm --entrypoint "./manage.py" \
            django loaddata climate-models

        docker-compose \
            -f docker-compose.yml \
            -f docker-compose.test.yml \
            run --rm --entrypoint "./manage.py" \
            django test --noinput --settings climate_change_api.settings_test

        createTestUser

        trap interceptError ERR
        echo "Testing endpoints"
        dredd

        deleteTestUser
    fi
    exit
fi
