#!/bin/bash

set -eu

cd `dirname "$0"`

function usage() {
    echo -n \
"Usage: $(basename "$0")

Run application tests.

"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        pushd ..

        ./scripts/console django './manage.py test'

        popd
    fi
    exit
fi
