#!/bin/bash

set -eu

function usage() {
    echo -n \
"Usage: $(basename "$0")

Run application tests.

"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        docker-compose \
            run --rm --entrypoint "./manage.py" \
            django migrate --noinput

        docker-compose \
            run --rm --entrypoint "./manage.py" \
            django loaddata scenarios

        docker-compose \
            run --rm --entrypoint "./manage.py" \
            django loaddata climate-models

        docker-compose \
            -f docker-compose.yml \
            -f docker-compose.test.yml \
            run --rm --entrypoint "./manage.py" \
            django test --noinput --settings climate_change_api.settings_test

        echo "Creating test user"
        echo "ClimateUser.objects.create_superuser('testuser@testing.com','thisisatest')" | ./scripts/console django "./manage.py shell_plus"

        echo "Testing endpoints"
        dredd

        echo "Deleting test user"
        echo "ClimateUser.objects.get(email='testuser@testing.com').delete()" | ./scripts/console django "./manage.py shell_plus"
    fi
    exit
fi
