# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-23 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import user_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='climateuser',
            name='burst_rate',
            field=models.CharField(default=user_management.models.get_default_burst_rate, max_length=10, verbose_name='burst rate'),
        ),
        migrations.AddField(
            model_name='climateuser',
            name='sustained_rate',
            field=models.CharField(default=user_management.models.get_default_sustained_rate, max_length=10, verbose_name='sustained rate'),
        ),
    ]
