# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-14 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20170223_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.CharField(max_length=255),
        ),
    ]
