# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-20 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_auto_20170414_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climateuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
